import { NextResponse } from "next/server"

// Extended Nepali voice commands with training data
const nepaliCommands = [
  {
    command: "ऋण खोज्नुहोस्",
    variations: ["लोन खोज्नुहोस्", "पैसा खोज्नुहोस्", "ऋण फेला पार्नुहोस्", "लोन देखाउनुहोस्", "उधार खोज्नुहोस्", "क्रेडिट खोज्नुहोस्"],
    intent: "search_loans",
    confidence: 0.95,
    response: "ऋण कार्यक्रमहरू खोजिरहेको छु...",
    category: "financial_search",
    usage_count: 0,
  },
  {
    command: "महिला सशक्तिकरण कार्यक्रम खोज्नुहोस्",
    variations: [
      "महिलाका लागि कार्यक्रम",
      "महिला सहायता",
      "महिला ऋण",
      "आमाहरूका लागि कार्यक्रम",
      "बहिनीहरूका लागि",
      "स्त्री सशक्तिकरण",
    ],
    intent: "search_women_programs",
    confidence: 0.9,
    response: "महिला सशक्तिकरण कार्यक्रमहरू खोजिरहेको छु...",
    category: "targeted_search",
    usage_count: 0,
  },
  {
    command: "युवा कार्यक्रम खोज्नुहोस्",
    variations: ["जवानहरूका लागि कार्यक्रम", "युवा ऋण", "युवा सहायता", "तरुणहरूका लागि", "युवा रोजगार", "युवा उद्यमी"],
    intent: "search_youth_programs",
    confidence: 0.88,
    response: "युवा कार्यक्रमहरू खोजिरहेको छु...",
    category: "targeted_search",
    usage_count: 0,
  },
  {
    command: "किसान कार्यक्रम खोज्नुहोस्",
    variations: ["कृषि कार्यक्रम", "खेतीपाती सहायता", "किसान ऋण", "कृषि ऋण", "खेती सहायता", "पशुपालन कार्यक्रम"],
    intent: "search_agriculture_programs",
    confidence: 0.87,
    response: "कृषि र किसान कार्यक्रमहरू खोजिरहेको छु...",
    category: "targeted_search",
    usage_count: 0,
  },
  {
    command: "व्यापारिक ऋण खोज्नुहोस्",
    variations: ["बिजनेस लोन", "व्यवसाय ऋण", "उद्योग ऋण", "व्यापार सहायता", "कम्पनी ऋण", "उद्यमी सहायता"],
    intent: "search_business_loans",
    confidence: 0.89,
    response: "व्यापारिक ऋण कार्यक्रमहरू खोजिरहेको छु...",
    category: "business_search",
    usage_count: 0,
  },
  {
    command: "इच्छा सूची खोल्नुहोस्",
    variations: ["विशलिस्ट खोल्नुहोस्", "मनपर्ने देखाउनुहोस्", "सुरक्षित कार्यक्रम", "सेभ गरिएको", "मेरो मनपर्ने", "पसन्दीदा कार्यक्रम"],
    intent: "open_wishlist",
    confidence: 0.92,
    response: "तपाईंको इच्छा सूची खोल्दै छु...",
    category: "navigation",
    usage_count: 0,
  },
  {
    command: "तुलना गर्नुहोस्",
    variations: ["कम्पेयर गर्नुहोस्", "मिलाउनुहोस्", "तुलना देखाउनुहोस्", "फरक देखाउनुहोस्", "भिन्नता देखाउनुहोस्", "तुलनात्मक अध्ययन"],
    intent: "compare_programs",
    confidence: 0.88,
    response: "कार्यक्रमहरूको तुलना गर्दै छु...",
    category: "navigation",
    usage_count: 0,
  },
  {
    command: "माइक्रोफाइनान्स खोज्नुहोस्",
    variations: ["साना ऋण", "सहकारी ऋण", "समूहिक ऋण", "सामुदायिक ऋण", "गरिब मैत्री ऋण", "सानो व्यापार ऋण"],
    intent: "search_microfinance",
    confidence: 0.86,
    response: "माइक्रोफाइनान्स कार्यक्रमहरू खोजिरहेको छु...",
    category: "financial_search",
    usage_count: 0,
  },
  {
    command: "सरकारी कार्यक्रम खोज्नुहोस्",
    variations: ["सरकारी सहायता", "सरकारी ऋण", "राज्य कार्यक्रम", "सरकारी योजना", "राष्ट्रिय कार्यक्रम", "सार्वजनिक कार्यक्रम"],
    intent: "search_government_programs",
    confidence: 0.91,
    response: "सरकारी कार्यक्रमहरू खोजिरहेको छु...",
    category: "government_search",
    usage_count: 0,
  },
  {
    command: "बैंक कार्यक्रम खोज्नुहोस्",
    variations: ["बैंकिङ सेवा", "बैंक ऋण", "बैंकिङ कार्यक्रम", "वित्तीय संस्था", "बैंक सहायता", "बैंकिङ सुविधा"],
    intent: "search_banking_programs",
    confidence: 0.87,
    response: "बैंकिङ कार्यक्रमहरू खोजिरहेको छु...",
    category: "financial_search",
    usage_count: 0,
  },
]

export async function GET() {
  return NextResponse.json({
    success: true,
    message: "नेपाली आवाज कमाण्डहरू सफलतापूर्वक लोड भयो",
    commands: nepaliCommands,
    total_commands: nepaliCommands.length,
    categories: ["financial_search", "targeted_search", "business_search", "navigation", "government_search"],
    language: "nepali",
    version: "1.0",
  })
}
